#!~/bin/bash
#==========================
#=====================================================
##
##         FILE:  Delitions_pipeline.sh
##
##        USAGE:  bash Delitions_pipeline.sh "File path here" "Path to sample names, one per line" "path to output" "threads" "ram" "SNP_and_samll_indel_calling = Y | N" "bed file with indel regions of intrest"
##
##  DESCRIPTION:  map with NOVO
##
##      OPTIONS:  SNP_calling = "Y | N"
## REQUIREMENTS:  FastQC, Trimmomatic, bwa, picard, samtools, bedtools, GenomeAnalysisTK, delly, pindel, bcftools, java-1.8, java runtime environment, lumpy, vcf-tools, R.3.3.0 (packages: data.table, dplyr, VariantAnnotation)
##         BUGS:  ---
##        NOTES:  Currently inefficient with much convoluted code, attempted not to leave bash as much as possible to make it easier to understand, kmer snp approach may be better depending on what you doing
##       AUTHOR:  Jason Limberis, lmbjas002@myuct.ac.za James Gallant
##      COMPANY:  UCT Stellenbosch VU Amsterdam
##      VERSION:  2.0
##      CREATED:  17/02/2017
##     REVISION:  ---
##         TODO:  Recode for novo, troubleshoot
##===============================================================================
# Dependancies and their paths
# setup environment
#module load java/jdk-1.8
export PATH=/home/user/Documents/genomics/programs/FastQC:$PATH
export PATH=/home/user/Documents/genommics/programs/Trimmomatic-0.36/trimmomatic-0.36.jar:$PATH
export PATH=/home/user/Documents/genomics/programs/picard:$PATH
#export PATH=~/bin/bwa-0.7.12:$PATH
#export PATH=~/bin/samtools-1.3.1:$PATH
#export PATH=~/bin/bedtools~/bin:$PATH
#export PATH=~/bin/GenomeAnalysisTK-3.3-0:$PATH
export PATH=~/bin~/bin/delly/src:$PATH
export PATH=/home/user/Documents/genomics/Deletions_only_pipeline/pindel:$PATH
#export PATH=/home/user/Documents/genomics/programs/
export PATH=/home/user/Documents/genomics/programs/lumpy-sv:$PATH
#export PATH=/home/lmbjas002/bin/bedtools/bin:$PATH
export PATH=/home/user/Documents/genomics/Deletions_only_pipeline/delly:$PATH
export PATH=/home/user/Documents/genomics/programs/bam2fastq-1.1.0:$PATH
export PATH=/home/user/Documents/genomics/programs/novocraft:$PATH 
export PATH=/home/user/Documents/genomics/programs/svtyper-master:$PATH
export PATH=/home/user/Documents/genomics/programs/SOAPdenovo2:$PATH



# awk
# R
# R packages:data.table, dplyr, tidyr
#Message for usage of the program
if  [ $1 == -h ]; 
then 
    echo "Welcome to the dark side of TB genomics. We are team Sam, let us be your guide."
    echo
    echo "Description: Targeted calling of structural variants using a split read approach"
    echo
    echo "Usage: <FastQ files> <Sample names> <output> <threads> <ram> <GATK SNP's>"
    echo
    echo
    
            echo "<FastQ fles>                    path to raw reads, rename to <samplename_R1_001.fastq.gz>"
            echo "<Sample names>                  path to text file with sample names, one per line."
            echo "<output>                        path to output."
            echo "<threads>                       Amount of cores to allocate (default is 6)."
            echo "<Ram>                           Amount of ram to allocate (default is 8)."
            echo "<GATK SNP's>                    SNP calling (Y or N)."
           
    echo
    exit 0
fi
#should start here
Script_dir=$(dirname "$0") #get directory where script is
# Script_dir=#"$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
F_dir="$1" #"File path here"
Files_IN="$2" #"Path to sample names, one per line"
Out_dir_in="$3" #"path to output"

#changable parameters
Trim=20 #$2
threads="$4"
ram="$5"
ulimit -m $(( $ram * 1024))
SNP_calling="$6"
Ref_name="${Script_dir}/references/CDC1551/CDC1551.fasta" #path to fasta
ref_index="${Script_dir}/references/CDC1551/CDC1551.ndx"
# echo -e "test\t2000\t3000" > temp_test
#region_of_interst="$7"
#echo $region_of_interst


# echo -e "test\t2000\t3000" > temp_test
# echo -e "test\t2000\t3000" > temp_test
Indels_of_interst="$7"
echo $Indels_of_interst
#this is a comma separated file with the indel name, the start position and the end position

mkdir "$Out_dir_in" 

#####################################################################################
##################################prepare reference##################################Fa
#####################################################################################mkdir
#all refs will be indexed and already in a folder - just here for info
# bwa index "$Ref_name"
# samtools faidx "$Ref_name"
# java -Xmx"${ram}"g -jar ~/bin/picard/picard.jar CreateSequenceDictionary \
#     R="$Ref_name" \
#     O="${Ref_name/.fasta/.dict}"
#####################################################################################

while read sample
 do
  echo "$sample"
  R1="${F_dir}/${sample}_R1_001.fastq.gz"
  R2="${F_dir}/${sample}_R2_001.fastq.gz"
  mkdir "${Out_dir_in}/${sample}"
  Out_dir="${Out_dir_in}/${sample}"
  Temp="${Out_dir}/Temp"
  mkdir "$Temp"
  Data="${Out_dir}/Data"
  mkdir "$Data"
  denovo="${Out_dir}/denovo"
  mkdir "$denovo"


  #fastQC sequence stats     James: It seems fastQC does not work fastqc "$R2unpaired" -o "$Data"  James: Fastqc does not run, cannot find files I do not know how to fix this
  fastqc "$R1" -o "$Data"
  fastqc "$R2" -o "$Data"

  #Trim sequences and clip adapters - Paired End        James: Trimmomatic tests out
  java -Xmx"${ram}g" -jar /home/user/Documents/genomics/programs/Trimmomatic-0.36/trimmomatic-0.36.jar PE -phred33 -threads "$threads" \
      "$R1" "$R2" \
      "${Temp}/${sample}_forward_paired.fq.gz" "${Temp}/${sample}_forward_unpaired.fq.gz" \
      "${Temp}/${sample}_reverse_paired.fq.gz" "${Temp}/${sample}_reverse_unpaired.fq.gz" \
      ILLUMINACLIP:"/home/user/Documents/genomics/programs/Trimmomatic-0.36/adapters/TruSeq2-PE.fa":2:30:15 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:"$Trim" MINLEN:30
  #Remove adapters
  #Remove leading low quality or N bases (below quality 3)
  #Remove trailing low quality or N bases (below quality 3)
  #Scan the read with a 4-base wide sliding window, cutting when the average quality per base drops below 15
  #Drop reads below the 30 bases long
  

  rm "${Temp}/${sample}_forward_unpaired.fq.gz"
  rm "${Temp}/${sample}_reverse_unpaired.fq.gz"
  
  #fastQC sequence stats                        
  fastqc "${Temp}/${sample}_forward_paired.fq.gz" -o "$Data"
  fastqc "${Temp}/${sample}_reverse_paired.fq.gz" -o "$Data"
  
  ##############
  #novo mapping##
  ##############
  
  # untar files first
  gunzip "${Temp}/${sample}_forward_paired.fq"
  gunzip "${Temp}/${sample}_reverse_paired.fq"
  
  novoalign -d "$ref_index" -f "${Temp}/${sample}_forward_paired.fq" "${Temp}/${sample}_reverse_paired.fq" -o SAM "@RG\\tID:${sample}\\tSM:${sample}\\tPL:Illumina" 2> "${Data}/${sample}_novo_stats.novodist"  > "${Temp}/${sample}_novo_paired.sam" 
  
  #rezip files
  mv "${Temp}/${sample}_forward_paired.fq" "${Data}/${sample}_forward_paired.fq"  
  mv "${Temp}/${sample}_reverse_paired.fq" "${Data}/${sample}_reverse_paired.fq"
  
  #validate and cleanup
  java -Xmx"${ram}"g -jar "/home/user/Documents/genomics/programs/picard.jar" ValidateSamFile \
       INPUT= "${Temp}/${sample}_novo_paired.sam" \
       OUTPUT="${Data}/${sample}_sam_validate.txt"
       
  #convert SAM into BAM and sort
  java -Xmx"${ram}"g -jar /home/user/Documents/genomics/programs/picard.jar SortSam \
      INPUT="${Temp}/${sample}_novo_paired.sam" \
      OUTPUT="${Temp}/${sample}_sorted.bam" \
      SORT_ORDER=coordinate \
      VALIDATION_STRINGENCY=LENIENT
      
  rm "${Temp}/${sample}_novo_paired.sam"
  
  #index fbam file 
  samtools index "${Temp}/${sample}_sorted.bam" 
  
  #Mark PCR Duplicates 
  java -Xmx"${ram}"g -jar /home/user/Documents/genomics/programs/picard.jar MarkDuplicates \
      INPUT="${Temp}/${sample}_sorted.bam" \
      OUTPUT="${Temp}/${sample}_sorted_dedup.bam" \
      VALIDATION_STRINGENCY=LENIENT \
      REMOVE_DUPLICATES=TRUE \
      ASSUME_SORTED=TRUE \
      M="${Temp}/${sample}_sorted_dedup.bam.txt"
      
  #Perform local realignment around indels to correct mapping-related artifacts with GATK
  #generate index  with picard
  java -Xmx"${ram}"g -jar /home/user/Documents/genomics/programs/picard.jar BuildBamIndex \
      I="${Temp}/${sample}_sorted_dedup.bam" \
      VALIDATION_STRINGENCY=LENIENT
      
  #Create a target list of intervals to be realigned with GATK
  java -jar /home/user/Documents/genomics/programs/GenomeAnalysisTK.jar -T  RealignerTargetCreator -R "${Ref_name}" -I "${Temp}/${sample}_sorted_dedup.bam" -o "${Temp}/${sample}_sorted_dedup.bam.list"    
      #-known indels if available.vcf
  
  #Realignment of target intervals        
  java -Xmx"${ram}"g -jar /home/user/Documents/genomics/programs/GenomeAnalysisTK.jar \
      -T IndelRealigner \
      -R "${Ref_name}" \
      -I "${Temp}/${sample}_sorted_dedup.bam" \
      -targetIntervals "${Temp}/${sample}_sorted_dedup.bam.list" \
      -o "${Temp}/${sample}_sorted_dedup_realigned.bam"
      
  #Sort with Samtools
  samtools sort -@ $threads -m "${ram}g" -O "bam" -T "working" -o "${Temp}/${sample}_sorted_dedup_realigned_sorted.bam" "${Temp}/${sample}_sorted_dedup_realigned.bam"
  
  #New index, sort with samtools 
  samtools index "${Temp}/${sample}_sorted_dedup_realigned_sorted.bam" 
  
  #Clean up
  mv "${Temp}/${sample}_sorted_dedup_realigned_sorted.bam" "${Data}/${sample}_sorted_dedup_realigned_sorted.bam"  
  mv "${Temp}/${sample}_sorted_dedup_realigned_sorted.bam.bai" "${Data}/${sample}_sorted_dedup_realigned_sorted.bam.bai"
  
  
  #############################################################################################################################
  #Snp calling has to be added here, will skip for now
  ############################################################################################################################# 
  
       if [[ $SNP_calling == "Y" || $SNP_calling == "y" ]]
       then
      # ##GATK INDEL small indels and SNPs                                                              James: 2 error messages from SNP caller but it runs: Check unified genotyper parameters
      #HaplotypeCaller - better at calling indels B
        java -Xmx"${ram}"g -jar /home/user/Documents/genomics/programs/GenomeAnalysisTK.jar \
            -T HaplotypeCaller \
            -ploidy 1 \
            -R "${Ref_name}" \
            -I "${Data}/${sample}_sorted_dedup_realigned_sorted.bam" \
            -stand_emit_conf 10 \
            -stand_call_conf 30 \
            --genotyping_mode DISCOVERY \
            -o "${Data}/${sample}_raw_variants_GATK_haplotype_caller.vcf"
            # -L targets.interval_list for subset
      
        #get depth 
        samtools depth "${Data}/${sample}_sorted_dedup_realigned_sorted.bam" > "${Data}/${sample}_sorted_dedup_realigned_sorted.coverage"
        ##samtools SNP and indel calling
        depth_cov=$(cat "${Data}/${sample}_sorted_dedup_realigned_sorted.coverage" |  awk '{sum+=$3} END { print sum/NR}')
        depth_cov=${depth_cov%.*}
        samtools mpileup -B -Q 20 -d $((depth_cov*2)) -C 50 -ugf "${Ref_name}" "${Data}/${sample}_sorted_dedup_realigned_sorted.bam" 2> "${Data}/${sample}_pileup.log" | /bin/bcftools/bcftools call -vc -Ob --threads "$threads" > "${Data}/${sample}.raw.bcf"
        #--ploidy "X" James: I get this as well shoudld we state --ploidy 1
        /bin/bcftools/bcftools view "${Data}/${sample}.raw.bcf" | /bin/bcftools/vcfutils.pl varFilter -d 10 -D $depth_cov > "${Data}/${sample}_raw_variants_Samtools.vcf"
        
        #remove unwanted stuff
        rm "${Data}/${sample}.raw.bcf"
        rm "${Data}/${sample}_sorted_dedup_realigned_sorted.coverage"

      ##########################################
      ##take intersection of GATK and samtools use bcftools under path /bin/bcftools/bcftools
      ## 
      ##########################################
      
      #this might have a problem with GATK
      bgzip "${Data}/${sample}_raw_variants_Samtools.vcf"
      tabix "${Data}/${sample}_raw_variants_Samtools.vcf.gz"
      bgzip "${Data}/${sample}_raw_variants_GATK_haplotype_caller.vcf"
      tabix "${Data}/${sample}_raw_variants_GATK_haplotype_caller.vcf.gz"
      
     

      #can filter here -e is exclude sites for which the expression is TRUE
      /bin/bcftools/bcftools filter -e "QUAL<30 && MIN(DP)<10" -O z -o "${Data}/${sample}_raw_variants_Samtools.filt.vcf.gz" "${Data}/${sample}_raw_variants_Samtools.vcf.gz"
      /bin/bcftools/bcftools filter -e "QUAL<30 && MIN(DP)<10" -O z -o "${Data}/${sample}_raw_variants_GATK_haplotype_caller.filt.vcf.gz" "${Data}/${sample}_raw_variants_GATK_haplotype_caller.vcf.gz"

      tabix "${Data}/${sample}_raw_variants_Samtools.filt.vcf.gz" 
      tabix "${Data}/${sample}_raw_variants_GATK_haplotype_caller.filt.vcf.gz"
      
      #JAmes:removed --threads since it interferes with options    
      /bin/bcftools/bcftools isec -n 2 -O z "${Data}/${sample}_raw_variants_Samtools.filt.vcf.gz" "${Data}/${sample}_raw_variants_GATK_haplotype_caller.filt.vcf.gz" -o "${Data}/${sample}_intersection.vcf"
      
      
    
      
      fi

  #################################################################################################################################
  #coverrage 
  #################################################################################################################################
 
#get coverage over the entire genome, can use this for circos plots later

  samtools view -b "${Data}/${sample}_sorted_dedup_realigned_sorted.bam" | genomeCoverageBed -bga -ibam stdin -g "${Ref_name}" > "${Data}/${sample}.all_coverage"

#this will get coverage from bedtools and take everythinh that has less than 10 reads into a file
  samtools view -b "${Data}/${sample}_sorted_dedup_realigned_sorted.bam" | genomeCoverageBed -bga -ibam stdin -g "${Ref_name}" |  awk '{if ($4 < 10) {printf ("%d\t%d\n",$3,$4);}}' > "${Data}/${sample}.low_coverage"

#get breakpoints i.e. zero coverage
  samtools view -b "${Data}/${sample}_sorted_dedup_realigned_sorted.bam" | genomeCoverageBed -bga -ibam stdin -g "${Ref_name}" |  awk '{if ($4 < 1) {printf ("%d\t%d\n",$3,$4);}}' > "${Data}/${sample}.zero_coverage"

#average depth coverage of genome
  samtools depth "${Data}/${sample}_sorted_dedup_realigned_sorted.bam" | awk '{sum+=$3} END { print "Average depth accross entire genome = ",sum/NR}' >> "${Data}/${sample}.average_coverage"
  
#Split reads for large deletions
  #Lumpy, Delly, Pindel
  
  ##############################################################################################################################
  #Pindel
  #to do: Add looking at subset with -C, -J
  ##############################################################################################################################
  
  #Picard to collect insert metrics for the mean insert size that we willl need to run pindel
  java -Xmx"${ram}"g -jar /home/user/Documents/genomics/programs/picard.jar CollectInsertSizeMetrics \
      I="${Data}/${sample}_sorted_dedup_realigned_sorted.bam" \
      O="${Data}/${sample}.picard.insert.metrics.tab" \
      HISTOGRAM_FILE="${Data}/${sample}.picard.insert.metrics.pdf"
      
  #This will set a variable for the mean from picard and then we echo everything we need in a text file for pindel
  mean=$(cat "${Data}/${sample}.picard.insert.metrics.tab" | awk '{print $5}' | sed -n '8p' | cut -f1 -d".")
  #echo -e "${Data}/${sample}_sorted_dedup_realigned_sorted.bam\t$mean\t${sample}" > "${Data}/pindel_samples.txt"
  
  ##
  #Sam2pindel since not bwa instead of echo to text?
  samtools view "${Data}/${sample}_sorted_dedup_realigned_sorted.bam" | sam2pindel - "${Data}/${sample}_output.pindel" "$mean" "${sample}" 0 Illumina-PairEnd

  
  #feed into pindel, you can do more with pindel read about it 
  pindel -c ALL --max_range_index 4 --min_perfect_match_around_BP 5 --min_num_matched_bases 15 --report_close_mapped_reads T -f "${Ref_name}" -p "${Data}/${sample}_output.pindel" -o "${Data}/${sample}_pindel"
  # -c 'gi|50953765|ref|NC_002755.2|Mycobacterium_tuberculosis_CDC1551':2,000,000-3,000,000 #to look at just a subset of the file
  
  #Convert to VCF file for viewing
  today=$(date +'%m%d%Y')
  pindel2vcf -G --min_size 100 -p "${Data}/${sample}_pindel_D" -r "$Ref_name" -R "CDC1551" -d "$today" -v "${Data}/${sample}_pindel_D.vcf"
  
  pindel2vcf -G --min_size 100 -p "${Data}/${sample}_pindel_INV" -r "$Ref_name" -R "CDC1551" -d "$today" -v "${Data}/${sample}_pindel_INV.vcf"
  
  pindel2vcf -G --min_size 100 -p "${Data}/${sample}_pindel_TD" -r "$Ref_name" -R "CDC1551" -d "$today" -v "${Data}/${sample}_pindel_TD.vcf"
  
  pindel2vcf -G --min_size 100 -p "${Data}/${sample}_pindel_LI" -r "$Ref_name" -R "CDC1551" -d "$today" -v "${Data}/${sample}_pindel_LI.vcf"
  
  pindel2vcf -G --min_size 100 -p "${Data}/${sample}_pindel_BP" -r "$Ref_name" -R "CDC1551" -d "$today" -v "${Data}/${sample}_pindel_BP.vcf"
  
   
  #pindel variant types D=deletion, INV=inversion, TD=tandem duplication, LI=large insertion BP=unasigned breakpoints
  
  #Delly segmentation faults using all the ususal tricks it might be cause I use novo
  
  #export OMP_NUM_THREADS=$threads
  
  #some problems, trying to subset and sort plus reindex. Sorted using picard, samtools is the other option. 
  
  
  #lumpy
  
  # Extract the discordant paired-end alignments.
  samtools view -b -F 1294 "${Data}/${sample}_sorted_dedup_realigned_sorted.bam" > "${Data}/${sample}_sample.discordants.unsorted.bam"
  
  # Extract the split-read alignments
  samtools view -h "${Data}/${sample}_sorted_dedup_realigned_sorted.bam" \
    | /home/user/Documents/genomics/programs/lumpy-sv/scripts/extractSplitReads_BwaMem -i stdin \
    | samtools view -Sb - \
    > "${Data}/${sample}_sample.splitters.unsorted.bam"
    
  lumpyexpress \
    -B "${Data}/${sample}_sorted_dedup_realigned_sorted.bam" \
    -S "${Data}/${sample}_sample.splitters.unsorted.bam" \
    -D "${Data}/${sample}_sample.discordants.unsorted.bam" \
    -o "${Data}/${sample}_lumpy.vcf"

  vcf-sort "${Data}/${sample}_lumpy.vcf" > "${Data}/${sample}_lumpy_sorted.vcf"
  
  #svtyper
  bgzip "${Data}/${sample}_lumpy_sorted.vcf"
  samtools index "${Data}/${sample}_sample.splitters.unsorted.bam"
  
  zcat "${Data}/${sample}_lumpy_sorted.vcf" | svtyper -B "${Data}/${sample}_sorted_dedup_realigned_sorted.bam" -S "${Data}/${sample}_sample.splitters.unsorted.bam" >  "${Data}/${sample}_lumpy_typed.vcf"
  
  vcf-sort "${Data}/${sample}_lumpy_typed.vcf" > "${Data}/${sample}_lumpy_typed_sorted.vcf"
  
  
  
  ############################################################################################################################
  #
  # extract unmapped reads for de novo assembly and subset bam files
  #
  ############################################################################################################################
   # bam2fastq --unaligned --output "${denovo}/${sample}_unmapped#.fq" --output "${denovo}/${sample}_unmapped#.fq" "${Data}/${sample}_sorted_dedup_realigned_sorted.bam"
  samtools view -b -f 4 "${Data}/${sample}_sorted_dedup_realigned_sorted.bam" > "${denovo}/${sample}_unmapped.bam"
  #some stats for later
  samtools flagstat "${Data}/${sample}_sorted_dedup_realigned_sorted.bam" > "${denovo}/${sample}_bamfile_flagstat.txt"
  samtools flagstat "${denovo}/${sample}_unmapped.bam" > "${denovo}/${sample}_unmapped_bamfile_flagstat.txt"

  
  #extract unmapped bam to fastq for kmergeni   
  java -Xmx"${ram}"g -jar "/home/user/Documents/genomics/programs/picard.jar"
    I="${denovo}/${sample}_unmapped.bam"
    F="${denovo}/${sample}_unmapped_1.fq"
    F2="${denovo}/${sample}_unmapped_2.fq"
    INCLUDE_NON_PRIMARY_ALIGNMENTS=true
    
  
    mv "${Data}/${sample}_forward_paired.fq" "${denovo}/${sample}_forward_paired.fq" 
    mv "${Data}/${sample}_reverse_paired.fq" "${denovo}/${sample}_reverse_paired.fq" 
  

  
    while read name start end
    do
  ########################
  
# 2628768-2630832
#mt2419=2628768
#mt2422=2630832
    #subset and remove reads with MAPQ less than 30 "-q 30""   
    
    
    ####################################
    #output for full assembly
    #output for unmaped assembly
    ####################################
   
  
  #extract unmapped reads from Bam
    
    echo "$name"
    
    #echo test
     {
        echo "$name"
        echo "$start" 
        echo "$end" 
        echo "$mean"  
        echo "$denovo" 
      } > "${denovo}/${sample}_${name}_echo_setup.txt" 
      
    
    
     #subset bam file 
    samtools view "${Data}/${sample}_sorted_dedup_realigned_sorted.bam" 'gi|50953765|ref|NC_002755.2|Mycobacterium_tuberculosis_CDC1551':$(($start-2000))-$(($end+2000)) > "${denovo}/${sample}_BWA_sorted_dedup_realigned_sorted_subset_${name}.bam" -b -h
    #build SOAP config file for user (unmapped reads)
  {
        echo "max_rd_len=100"
        echo "[LIB]"
        echo "avg_ins=$mean"
        echo "reverse_seq=0"
        echo "asm_flags=3"
        echo "rank=1"
        echo "pair_num_cutoff=3"
        echo "map_len=32"
        echo "b=${denovo}/${sample}_BWA_sorted_dedup_realigned_sorted_subset_${name}.bam"
    } > "${denovo}/${sample}_${name}_SOAP_subset_config.txt"
    
    {
        echo "max_rd_len=100"
        echo "[LIB]"
        echo "avg_ins=$mean"
        echo "reverse_seq=0"
        echo "asm_flags=3"
        echo "rank=1"
        echo "pair_num_cutoff=3"
        echo "map_len=32"
        echo "q1=${denovo}/${sample}_forward_paired.fq"
        echo "q2=${denovo}/${sample}_reverse_paired.fq"
    } > "${denovo}/${sample}_SOAP_full_config.txt"
    
    {
        echo "max_rd_len=100"
        echo "[LIB]"
        echo "avg_ins=$mean"
        echo "reverse_seq=0"
        echo "asm_flags=3"
        echo "rank=1"
        echo "pair_num_cutoff=3"
        echo "map_len=32"
        echo "q1=${denovo}/${sample}_unmapped_1.fq"
        echo "q2=${denovo}/${sample}_unmapped_2.fq"
    } > "${denovo}/${sample}_SOAP_unmapped_config.txt"



    # now do local alignment and draw figure
    #subset reference
    #start_ref=$(($start-2000))
    #end_ref=$(($end+2000))
    samtools faidx "${Ref_name}" 'gi|50953765|ref|NC_002755.2|Mycobacterium_tuberculosis_CDC1551':$(($start-2000))-$(($end+2000)) > "${denovo}/${name}_ref_area_intrest.temp.fasta"
    samtools faidx "${denovo}/${name}_ref_area_intrest.temp.fasta"
    
    #index subset

    #ref_area_intrest="${denovo}/${name}_ref_area_intrest.temp.fasta"
    
    #remove name as rmpreviously aligh=ned to different ref so this will cause comlications

    #sed '1s/.*/>gi|50953765|ref|NC_002755.2|Mycobacterium_tuberculosis_CDC1551/' $ref_area_intrest > "${denovo}/${name}_ref_area_intrest.fasta"
    #ref_area_intrest="${denovo}/${name}_ref_area_intrest.fasta"

    
    #change this to bowtie2 as it is more splice aware? or something that uses larger reads, still working on this

 #velvetoptimiser '/home/user/Desktop/test_data/denovo' --v -s 15 --e 25 --t 6 --a --d -f "-fastq.gz -shortPaired -separate '/home/user/Desktop/test_data/test_subset_unmapped__1.fq.gz' '/home/user/Desktop/test_data/test_subset_unmapped__1.fq.gz'" 
#################################################################################################################################
#using SOAPdenovo2
#Requires a Config file requires certain parameters
#max_rd_len=100
#[lib]
#1) avg_ins=300
##Illumina insert size is usually around 300 bp use 300
#2) reverse_seq=0
#3) asm_flags=3
#4) rd_len_cutof=60
#5) rank=1
#6) pair_num_cutoff=3
#7) map_len=32
#q1=fastq file 1 PE
#q2=fastq file 2
#reads the files but nothing usefull happens
#SOAPdenovo-63mer all -s '/home/user/Desktop/test_data/denovo/test.config' -o "test_graph" -R -F -K 23
#avg_ins=300

#reverse_seq=0

#asm_flags=3

#rd_len_cutof=60

#rank=1

#pair_num_cutoff=3

#map_len=32

########################################################################
#RDAnalyzer
#SpoTyping xiaeryu

 rm -r "$Temp"
 done<"$Indels_of_interst"
 done<"$Files_IN"
 
 echo "Analysis done"

exit 0
